### ISSUE TITLE
Install a specific version of databricks cli?

### ISSUE THREAD

**Issue by AHJiapengZhang** [databricks/homebrew-tap#56]
Is this possible. Right now my workaround is to tap this repo and git checkout a history commit and then brew install, which is really inconvenient. Is there any other easier way?

**Comment by pietern** [comment]
I searched around a bit and didn't find an easier way to do this.

Could you explain why you need to install an older version?

**Comment by pietern** [comment]
I investigated how to best install a previous version of the CLI with Homebrew and wrote it up in #68.

It is possible after all, as long as you know which Homebrew commands to run.
